apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: demo-interop-template
spec:
  params:
    - name: architecture
    - name: ocp_build
    - name: layered_product_version
    - name: ocp_version
    - name: template_version
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: pipelinerun-with-taskspec-
      spec:
        workspaces:
        - name: kubeconfig
          secret:
            secretName: kubeconfig
        pipelineSpec:
          workspaces:
          - name: kubeconfig
          tasks:
            - name: echo-artifacts
              taskSpec:
                results:
                - name: artifacts
                  description: Artifatcs of your workloads
                steps:
                  - name: echo
                    image: registry.redhat.io/ubi8/ubi-minimal
                    script: |
                      #!/usr/bin/env bash

                      function produce_results() {
                          echo -n "find your dummy artifacts here: https://dummy-artifacts-of-your-test-result" > $(results.artifacts.path)
                      }

                      trap produce_results ERR EXIT
                      echo "$(tt.params.architecture)"
                      echo "dev-preview/$(tt.params.ocp_build)"
                      echo "$(tt.params.layered_product_version)"
                      echo "$(tt.params.ocp_version)"
                      echo "$(tt.params.template_version)"
          finally:
          - name: finally
            workspaces:
            - name: kubeconfig
              workspace: kubeconfig
            params:
            - name: artifacts
              value: $(tasks.echo-artifacts.results.artifacts)
            taskSpec:
              workspaces:
              - name: kubeconfig
              params:
              - name: artifacts
                description: artifatcs of previous taskruns
              steps:
                - name: send-umb-notification
                  env:
                    - name: UMB_WEBHOOK_URL
                      value: "http://umb-service-umb.apps.cicd.tekton.codereadyqe.com/produce"
                    - name: PIPELINERUN
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.labels['tekton.dev/pipelineRun'] 
                    - name: LOG_URL
                      value: "openshift"
                    - name: VERSION
                      value: $(tt.params.layered_product_version)
                    - name: XUNIT_URLS
                      value: $(params.artifacts)
                    - name: KUBECONFIG
                      value: $(workspaces.kubeconfig.path)/kubeconfig  
                  image: quay.io/praveen4g0/umb-notifier:latest
                  command: ["/code/send-umb-interop-notifier.py"]