kind: Build
apiVersion: build.openshift.io/v1
metadata:
  name: umb
  labels:
    app: umb
    template: umb-template
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/praveen4g0/umb.git'
      ref: 'main'
  strategy:
    type: Docker
    dockerStrategy:
      env:
        - name: GIT_SSL_NO_VERIFY
          value: 'true'
  output:
    to:
      kind: ImageStreamTag
      name: 'umb:latest'
  resources:
    limits:
      memory: 1Gi